#tag::oauth2[]
micronaut:
  application:
    name: complete
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        google: # <1>
          client-id: '${OAUTH_CLIENT_ID}'  # <2>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <3>
          openid:
            issuer: 'https://accounts.google.com' # <4>
    endpoints:
      logout:
        get-allowed: true # <5>
#end::oauth2[]
app:
  hosted-domain: 'objectcomputing.com'
