#tag::oauth2[]
micronaut:
  application:
    name: complete
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        google: # <1>
          client-id: '290477064382-nt0b8v8bkeeffqppv965prbt70fhficf.apps.googleusercontent.com'  # <2>
          client-secret: 'g_tMz44_IHCigG5ffNt5ISBp' # <3>
          openid:
            issuer: 'https://accounts.google.com' # <4>
    endpoints:
      logout:
        get-allowed: true # <5>
#end::oauth2[]
app:
  hosted-domain: 'objectcomputing.com'
