#tag::oauth2[]
micronaut:
  application:
    name: complete
  security:
    enabled: true # <1>
    oauth2:
      enabled: true
      clients:
        google: # <2>
          client-id: '${OAUTH_CLIENT_ID}'  # <3>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <4>
          openid:
            issuer: 'https://accounts.google.com' # <5>
    token:
      jwt:
        enabled: true # <6>
        cookie:
          enabled: true # <7>
        signatures:
          secret:
            generator: 
              secret: pleaseChangeThisSecretForANewOne 
endpoints:
      logout:
        enabled: true # <8>
        get-allowed: true # <9>

#end::oauth2[]
