#tag::oauth2[]
micronaut:
  application:
    name: complete
  security:
    oauth2:
      enabled: true
      clients:
        google: # <1>
          client-id: '${OAUTH_CLIENT_ID}'  # <2>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <3>
          openid:
            issuer: 'https://accounts.google.com' # <4>
    token:
      jwt:
        cookie:
          enabled: true # <5>
        signatures:
          secret:
            generator: # <6>
              secret: pleaseChangeThisSecretForANewOne <7>
    endpoints:
      logout:
        enabled: true # <8>
        get-allowed: true # <9>
#end::oauth2[]
